export enum DictNameEnum {
  ROLE_REL_TYPE = "ROLE_REL_TYPE",
  USE_STATE = "USE_STATE",
  // TODO 待添加
  LABEL_POSITION = "LABEL_POSITION",
  FORM_FIELD_TYPE = "FORM_FIELD_TYPE",
  BOOLEAN = "BOOLEAN"
}
